app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', lambda request: redirect('home/', permanent=False)),
    path('', include('schedule_advisor.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('logout', LogoutView.as_view()),
]

urlpatterns += staticfiles_urlpatterns()

schedule_advisor/urls.py
from django.urls import path, include

from . import views

app_name = 'schedule_advisor'
urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('courses/', views.get_courses, name="courses"),
    path('courses/<int:id>/', views.course_detail, name="course_detail"),
    path('schedule/', views.schedule, name='schedule'),
    path('<int:user_id>/<int:course_id>/add/', views.add_course, name='add_course'),
    path('<int:user_id>/<int:course_id>/drop/', views.remove_course, name='remove_course'),
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('<int:user_id>/cart_view/', views.view_student_cart, name='student_cart'),
    path('<int:user_id>/approved/', views.approve, name='approval'),
    path('<int:user_id>/rejected/', views.reject, name='rejection'),
    path('<int:user_id>/submit/', views.submit_schedule, name='submit_schedule')
]
# path('home/', views.index, name='home'),

schedule_advisor/models.py
# from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, AbstractUser


class Instructor(models.Model):
    name = models.CharField(max_length=100, default='N/A')
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name


class Meeting(models.Model):
    days = models.CharField(max_length=100, default='N/A')
    st_time = models.CharField(max_length=10, default='N/A')
    end_time = models.CharField(max_length=10, default='N/A')
    building = models.CharField(max_length=100, default='N/A')
    room = models.CharField(max_length=100, default='N/A')
    st_date = models.CharField(max_length=10, default='N/A')
    end_date = models.CharField(max_length=10, default='N/A')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['days', 'st_time', 'end_time', 'building', 'room', 'st_date', 'end_date'],
                                    name="%(app_label)s_%(class)s_unique")
        ]

    def __str__(self):
        return f'{self.days}, {self.st_time}-{self.end_time}, {self.building} {self.room}'


class Course(models.Model):
    crse_id = models.IntegerField(default=0)
    descr = models.CharField(max_length=300)
    subject = models.CharField(max_length=5)
    class_capacity = models.IntegerField(default=0)
    meeting = models.ManyToManyField(Meeting)
    class_section = models.CharField(default='', max_length=20)  # test comment
    class_nbr = models.CharField(default='00000', max_length=10)
    instructors = models.ManyToManyField(Instructor)
    units = models.CharField(default='0', max_length=10)
    term = models.CharField(max_length=300, default='N/A')
    # times = models.CharField(max_length=300, default='N/A')
    instruction_mode = models.CharField(max_length=100, default='N/A')
    enrollment = models.IntegerField(default=0)
    catalog_number = models.CharField(max_length=10, default='0000')
    section_type = models.CharField(max_length=10, default='Lecture')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['term', 'class_nbr', 'subject', 'catalog_number'],
                                    name="%(app_label)s_%(class)s_unique")
        ]

    def __str__(self):
        return self.descr  # Will need to change this eventually but should be fine for now


class ShoppingCart(models.Model):
    courses = models.ManyToManyField(Course)


# Create your models here.
class User(AbstractUser):
    # we can just have 1 boolean, I think just 1 is fine. True for teacher, false for student
    # is_student = models.BooleanField('student status', default=False)
    is_teacher = models.BooleanField('teacher status', default=False)
    shopping_cart = models.ManyToManyField(Course)
    status = models.IntegerField(default=-2)
    message = models.CharField(max_length=5000, default='')



class Subject(models.Model):
    name = models.CharField(max_length=10, unique=True)
    descr = models.CharField(max_length=100, default='N/A')

    def __str__(self):
        return self.name

schedule_advisor/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import HttpResponse, render, get_object_or_404
from django import forms
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SF
from schedule_advisor.models import Course, Meeting, Instructor, Subject, User, ShoppingCart
import requests, string
from django.urls import reverse
from django.views import generic
from django.contrib import messages


class MyCustomSocialSignupForm(SF):
    is_teacher = forms.BooleanField(required=False, label='Are you a teacher?:')

    def save(self, request):
        user = super(MyCustomSocialSignupForm, self).save(request)
        user.is_teacher = self.cleaned_data['is_teacher']
        user.save()
        # You must return the original result.
        return user


class MyCustomSignupForm(SignupForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    is_teacher = forms.BooleanField(required=False, label='Please check this box if you are a teacher:')

    def save(self, request):
        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(MyCustomSignupForm, self).save(request)

        # Add your own processing here.
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_teacher = self.cleaned_data['is_teacher']
        user.save()
        # You must return the original result.
        return user


def index(request):
    userList = User.objects.all()
    return render(request, 'schedule_advisor/home.html', {'users': userList})


def login(request):
    return render(request, 'schedule_advisor/login.html')


def schedule(request):
    return render(request, 'schedule_advisor/schedule.html')


def add_course(request, user_id, course_id):
    user = get_object_or_404(User, pk=user_id)
    course_added = get_object_or_404(Course, id=course_id)
    print('DSNDOSd')
    print(user.username)
    print(course_added)
    print('Doing something')
    if course_added not in user.shopping_cart.all():
        print('IF')
        user.shopping_cart.add(course_added)

    if schedule_conflict(user):
        user.shopping_cart.remove(course_added)
        messages.error(request, "Error, "+course_added.descr +" has a Time Conflict with your Current Schedule")
    else:
        user.status = -2
        messages.success(request, "Success, "+course_added.descr +" has been Added to your Cart")
    print(user.shopping_cart.count())
    user.save()
    print('DONE')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def remove_course(request, user_id, course_id):
    user = get_object_or_404(User, pk=user_id)
    course = get_object_or_404(Course, id=course_id)
    # print('DSNDOSd')
    # print(user.username)
    # print(course)
    # print('Doing something')
    if course in user.shopping_cart.all():
        # print('IF')
        user.shopping_cart.remove(course)
        user.status = -2
    # print(user.shopping_cart.count())
    user.save()
    # print('DONE')
    messages.success(request, "Success, "+course.descr +" has been Removed to your Cart")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def get_subjects(request):
    url = "https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearchOptions?institution=UVA01"
    subs = requests.get(url).json()
    Subject.objects.all().delete()
    all_subjects = {}
    for sub in subs['subjects']:
        subject_data = None
        if Subject.objects.filter(name=sub['subject']).exists():
            subject_data = Subject.objects.filter(name=sub['subject'])[0]
        else:
            subject_data = Subject(name=sub['subject'], descr=sub['descr'])
            subject_data.save()
        all_subjects = Subject.objects.all().order_by('name')
    return all_subjects


def get_courses(request):
    # https://dev.to/yahaya_hk/how-to-populate-your-database-with-data-from-an-external-api-in-django-398i

    # Course.objects.all().delete()
    all_courses = {}
    filters = {}
    all_subs = get_subjects(request)
    if 'subject' in request.GET:
        subj = request.GET['subject']
        if subj != '':
            filters['subject'] = subj
    if 'catalog_num' in request.GET:
        cat_num = request.GET['catalog_num']
        if cat_num != '':
            filters['catalog_number'] = cat_num
    if 'instructor' in request.GET:
        inst = request.GET['instructor']
        if inst != '':
            filters['instructors'] = inst
    if 'class_nbr' in request.GET:
        class_nbr = request.GET['class_nbr']
        if class_nbr != '':
            filters['class_nbr'] = class_nbr
    if 'im' in request.GET:
        im = request.GET['im']
        if im != '':
            filters['instruction_mode'] = im
    if 'descr' in request.GET:
        descr = request.GET['descr']
        if descr != '':
            filters['descr'] = descr
    if 'instructors' in filters.keys():
        instr = filters['instructors']
        del filters['instructors']
        all_courses = Course.objects.filter(instructors__name__contains=instr, **filters).order_by('catalog_number')
    elif len(filters.keys()) > 0:
        all_courses = Course.objects.filter(**filters).order_by('catalog_number')
    return render(request, 'schedule_advisor/course.html', {"all_courses": all_courses, "all_subjects": all_subs})


def course_detail(request, id):
    course = Course.objects.get(id=id)
    return render(
        request,
        'schedule_advisor/course_detail.html',
        {'course': course}
    )


def shopping_cart(request):
    return render(request, 'schedule_advisor/shopping_cart.html')


def view_student_cart(request, user_id):
    user = User.objects.get(pk=user_id)
    print(user.username)
    return render(request, 'schedule_advisor/student_cart.html', {'student': user})


def approve(request, user_id):
    print(user_id)
    user = get_object_or_404(User, pk=user_id)
    user.status = 1
    user.message = "Your Schedule has been approved!"
    user.save()
    return HttpResponseRedirect(reverse('schedule_advisor:home'))


def reject(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.status = -1
    user.message = request.GET['rejection']
    user.save()
    return HttpResponseRedirect(reverse('schedule_advisor:home'))


def submit_schedule(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if schedule_conflict(user):
        user.status = -2
        user.message = 'Your schedule is not valid, there is a scheduling conflict.'
        user.save()

    else:
        user.status = 0
        user.message = 'Your schedule has been submitted to your advisor! \nAwaiting approval...'
        user.save()
    return HttpResponseRedirect(reverse('schedule_advisor:home'))

def schedule_conflict(user):
    for course in user.shopping_cart.all():
        for comparing_course in user.shopping_cart.all():
            for course_meeting in course.meeting.all():
                for comparing_course_meeting in comparing_course.meeting.all():
                    if course.class_nbr != comparing_course.class_nbr:
                        if len(course_meeting.days) != 0 and len(comparing_course_meeting.days) !=0:
                            if ('Mo' in course_meeting.days and 'Mo' in comparing_course_meeting.days) or ('Tu' in course_meeting.days and 'Tu' in comparing_course_meeting.days) or('We' in course_meeting.days and 'We' in comparing_course_meeting.days) or('Th' in course_meeting.days and 'Th' in comparing_course_meeting.days) or('Fr' in course_meeting.days and 'Fr' in comparing_course_meeting.days):
                                first_course_starting_time = Convert_Time_String_into_Int(course_meeting.st_time)
                                first_course_ending_time = Convert_Time_String_into_Int(course_meeting.end_time)
                                second_course_starting_time = Convert_Time_String_into_Int(comparing_course_meeting.st_time)
                                second_course_ending_time = Convert_Time_String_into_Int(comparing_course_meeting.end_time)

                                if (first_course_starting_time >= second_course_starting_time and first_course_starting_time <= second_course_ending_time):
                                    return True
                                if (second_course_starting_time>= first_course_starting_time and second_course_starting_time <= first_course_ending_time):
                                    return True

    return False


def Convert_Time_String_into_Int(meeting_time):
    return 100 * ((int)(meeting_time[0:2])) + ((int)(meeting_time[3:5]))

schedule_advisor/templates/schedule_advisor/base.html
{% load bootstrap5 %}
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en-US">
    <head>
	<style>
		.navbar {
			background-color: #333;
			overflow: hidden;
			padding: 20px; /* Add padding to the navbar */
		}

		.navbar a {
			float: left;
			color: #f2f2f2;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
			font-size: 17px;
		}

		.navbar a:hover {
			background-color: #ddd;
			color: black;
		}
        .right {
            margin-left: auto;
        }

		.active {
			background-color: #4CAF50;
			color: white;
		}
	</style>
</head>
        <title>{% block title %}(){% endblock title %}</title>
        {% bootstrap_css %}
    </head>
    <body>
        <nav class="navbar navbar-expand navbar-darkpyth bg-dark">
            <a class="navbar-brand" href="{% url 'schedule_advisor:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  {% if user.is_teacher == False %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'schedule_advisor:schedule' %}">My Schedule</a>
                </li>
                  {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'schedule_advisor:courses' %}">Courses</a>
                </li>
                  {% if user.is_teacher == False %}
                  <li class="nav-item">
                  <a class="nav-link" href="{% url 'schedule_advisor:shopping_cart'%}">Shopping Cart</a>
                </li>
                  {% endif %}
              <!--</ul>-->
                {% if user.is_authenticated %}
              <!--<ul class="nav navbar-nav navbar-right">-->
                <li class="right">
                  <a class="nav-link" href="{% url 'schedule_advisor:login' %}">Log Out</a>
                </li>
              <!--</ul>-->
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'schedule_advisor:login' %}">Login</a>
                </li>
              </ul>
                {% endif %}
            </div>
          </nav>

        {% block content %}
        {% endblock content %}
        {% bootstrap_javascript %}
    </body>
</html>

schedule_advisor/templates/schedule_advisor/course.html
{% extends 'schedule_advisor/base.html'%}
{% load static %}
{% load socialaccount %}
{% block title %}Course Search{% endblock %}
{% block content %}
    {% if user.is_authenticated == False %}
        <br>
        <p>Please log in to view all of the courses!</p>
    {% endif %}
    {% if user.is_authenticated %}
        {% if user.is_teacher == False %}
        <div class="alert" id="success-banner" style="display: block; background-color: powderblue">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            Current Cart: {% for course in user.shopping_cart.all %}
                {{course.descr}}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </div>
        {% endif %}
{% if messages %}
<div class="messages" >
    {% for message in messages %}
    {% if message.tags == 'success'%}
        <div class="alert {{ message.tags }} alert-dismissible" role="success-banner" style="display: block; background-color: green">
             <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{ message }}
          </div>
        {% endif %}
    {% if message.tags == 'error' %}
        <div class="alert {{ message.tags }} alert-dismissible" role="error-banner" style="display: block; background-color: red">
             <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{ message }}
          </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}
        <div class = "container">
          <br>
          <h2 class = "text-center">Search for Courses</h2>
          <br>
          <form method="GET">
              <div class="text-center">
              <select id="subject" name="subject" class="text-center">
                  <option value="" disabled selected>Select the subject</option>
                  {% for sub in all_subjects %}
                  <option value={{sub.name}}>{{sub.descr}}</option>
                  {% endfor %}
              </select>
              </div>
              <div class="text-center">
              <select id="im" name="im" class="text-center">
                  <option value="" disabled selected>Select Instruction Mode</option>
                  <option value="P">In Person</option>
                  <option value="OA">Online Asynchronous</option>
                  <option value="RR">Research Rate</option>
              </select>
              </div>
              <br>
              <div style="text-align: center;">
                <table class="table mx-auto" style="width: 800px;">
                    <tr>
                        <td class="text-end"><label><b> Search by Catalog Number: </b> </label></td>
                        <td><input type="number" id="catalogNumBox" min="1000" max="9999" name = "catalog_num" value=parseURLGetCatalogNum() placeholder="(Ex: 3240)" class="text-center" style="width: 400px;" size = "32"></td>
                    </tr>
                    <tr>
                        <td class="text-end"><label><b> Search by Class Number:  </b> </label></td>
                        <td><input type="number" id="classNumBox" min="10000" max="99999" name = "class_nbr" placeholder="(Ex: 16031)" class="text-center" style="width: 400px;" size = "32"></td>
                    </tr>
                    <tr>
                        <td class="text-end"><label><b>Search by EXACT Course Description: </b></label></td>
                        <td><input type = "text" id="descrBox" name = "descr" placeholder="(Ex: Introduction to Programming)" class = "text-center" style="width: 400px;" size = "32"></td>
                    </tr>
                    <tr>
                        <td class="text-end"><label> <b>Search by Instructor Name: </b></label></td>
                        <td><input type="text" name="instructor" id="instrBox" placeholder="(Ex: Tom Horton)" style="width: 400px;"class="text-center"></td>
                    </tr>
                </table>
              </div>
              <br>
              <div class="text-center"><button type = "submit" class = "btn-success ">SEARCH COURSES</button></div><br>
          </form>
            <div class="row">
                {% if all_courses|length == 0 %}
                    {% if "catalog_num" in request.get_full_path %}
                    <div class="row justify-content-center">
                        <div class="card">
                            <div class="card-body text-center">
                                <b><p class="card-title">Oops! We couldn't find what you were looking for. Please try again!</p></b>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% endif %}
          {% for course in all_courses %}
              <div class="col-md-4 col-sm-6 col-lg-3">
                <div class="card">
                    <div class="card-body text-center">
                      <b><p class="card-title">{{ course.subject }} {{ course.catalog_number}}</p></b>
                        <p>{{course.descr}}</p>
                        {% for meet in course.meeting.all %}
                            {% if meet.days|default:'' == '-' and meet.st_time|default:'' == ':' and meet.end_time|default:'' == ':' %}
                                <p>No official meeting time.</p>
                            {% else %}
                            <p>{{meet.days}}: {{meet.st_time}}-{{meet.end_time}}</p>
                            {% endif %}
                            {% endfor %}
                        <u><p>{{course.class_nbr}}</p></u>
                        <p>{{course.enrollment}}/{{course.class_capacity}}</p>
                        {% for instructor in course.instructors.all %}
                            <p>{{instructor.name}} - {{instructor.email}}</p>
                        {% endfor %}
                      <hr>
                        {% if user.is_teacher == False %}
                            {% if course not in user.shopping_cart.all %}
                            <form action="{% url 'schedule_advisor:add_course' user.id course.id %}" method="GET">
                                <button type="submit" onclick="displayBanner()" class="btn btn-success btn-sm">Add Class</button>
                            </form>
                            {% else %}
                            <form action="{% url 'schedule_advisor:remove_course' user.id course.id %}" method="GET">
                                <button type="submit" onclick="displayBanner()" class="btn btn-danger btn-sm">Remove Class</button>
                            </form>
                            {% endif %}
                        {% endif %}
                        <br>
                            <a href="/courses/{{course.id}}"
                        ><input
                        type="submit"
                        value="Learn More"
                        class="btn btn-danger btn-sm"
                        type="button"
                        /></a>
                    </div>
                </div>
                <br><br><br>
              </div>
          {% endfor %}
            </div>
        </div>
    {% else %}
        <button class="btn btn-outline-info"><a href="{% provider_login_url 'google'%}">Login</a></button>
    {% endif %}
<script>
    var hasSearched = false;
    var myElement = document.getElementById("success-banner");
function displayBanner() {
    hasSearched = true;
    if (hasSearched) {
        myElement.textContent += "If you don't see the class you just added, there was probably a schedule conflict!";
      }
}
function parseURLGetInstructor() {
        var url = window.location.href;
        const regex = new RegExp(/instructor=([^&]*)/);
        const match = url.match(regex);
        if (match) {
            return match[1].replace(/\+/g, " ");
        }
        return undefined;
}
      const instrBox = document.getElementById("instrBox");
        if (parseURLGetInstructor() !== undefined) {
      instrBox.value = parseURLGetInstructor();
    } else {
      instrBox.value = "";
    }

function parseURLGetDescription() {
        var url = window.location.href;
        const regex = new RegExp(/descr=([^&]*)/);
        const match = url.match(regex);
        if (match) {
            return match[1].replace(/\+/g, " ");
        }
        return undefined;
}
      const descrBox = document.getElementById("descrBox");
        if (parseURLGetDescription() !== undefined) {
      descrBox.value = parseURLGetDescription();
    } else {
      descrBox.value = "";
    }
function parseURLGetClassNum() {
        var url = window.location.href;
        const match = url.match(/class_nbr=(\d{5})/);
        if (match) {
            return match[1];
        }
        return undefined;
      }
      const classBox = document.getElementById("classNumBox");
        classBox.value = parseURLGetClassNum();
function parseURLGetCatalogNum() {
        var url = window.location.href;
        const match = url.match(/catalog_num=(\d{4})/);
        if (match) {
            return match[1];
        }
        return undefined;
      }
        const catBox = document.getElementById("catalogNumBox");
        catBox.value = parseURLGetCatalogNum();
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>
{% endblock %}

schedule_advisor/templates/schedule_advisor/course_detail.html
{% extends 'schedule_advisor/base.html'%}
{% load static %}
{% block content %}

{% if messages %}
<div class="messages" >
    {% for message in messages %}
    {% if message.tags == 'success'%}
        <div class="alert {{ message.tags }} alert-dismissible" role="success-banner" style="display: block; background-color: green">
             <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{ message }}
          </div>
        {% endif %}
    {% if message.tags == 'error' %}
        <div class="alert {{ message.tags }} alert-dismissible" role="error-banner" style="display: block; background-color: red">
             <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{ message }}
          </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

<div class = "container"> 
    <br><br>
    <div class="row">
        <div class="col-md-7 shadow-lg p-3 mb-5 bg-white rounded">
          <h1 class="my-3 text-center">{{course.subject}} {{course.catalog_number}}</h1>
            <h3 class="my-3 text-center">{{course.descr}}</h3>
            <h7 class="my-3 text-center">{{course.units}} credit(s)</h7>
            {% for meet in course.meeting.all %}
                <p>Timing: {{meet.days}}: {{meet.st_time}}-{{meet.end_time}}</p>
            <p>Dates: {{meet.st_date}}-{{meet.end_date}}</p>
            <p>Location: {{meet.building}} {{meet.room}}</p>
            {% endfor %}
            <p>Instructor(s)</p>
            <ul>
            {% for instruct in course.instructors.all %}
                <li><p>{{instruct.name}}</p> <ul>
                    <li><p>{{instruct.email}}</p></li>
                </ul></li>
            {% endfor %}
                </ul>
            <p>Section Type: {{course.section_type}}</p>
            <p>Seats Filled: {{course.enrollment}}/{{course.class_capacity}}</p>
            <p>Course Numerical Information</p>
            <ul>
                <li>Course ID: {{course.crse_id}}</li>
                <li>Class Section: {{course.class_section}}</li>
                <li>Class Number: {{course.class_nbr}}</li>
            </ul>
            {% if user.is_teacher == False %}
                {% if course not in user.shopping_cart.all %}
                    <form action="{% url 'schedule_advisor:add_course' user.id course.id %}" method="GET">
                        <button type="submit" class="btn btn-success btn-sm">Add Class</button>
                    </form>
                    {% elif course in user.shopping_cart.all %}
                    <form action="{% url 'schedule_advisor:remove_course' user.id course.id %}" method="GET">
                        <button type="submit" class="btn btn-danger btn-sm">Remove Class</button>
                    </form>
                {% endif %}
            {% endif %}
            <br>
            <button onclick="history.back()" class="btn btn-danger btn-sm float-right">Return to Course Search</button>
        </div>
    </div>
</div>

{% endblock %}

schedule_advisor/templates/schedule_advisor/student_cart.html
{% extends 'schedule_advisor/base.html'%}
{% load static %}
{% load socialaccount %}
{% block content %}
    <div class="container">
        <h2 class = "text-center">Evaluate the Student's Schedule for the Upcoming Semester! </h2>

   
<div class="row">
    <br>
    <div class="container">
    <form action="{% url 'schedule_advisor:rejection' student.id %}" method="GET">
        <label for="rejection">Enter Information about Rejection:</label>
        <br>
        <input type="text" name="rejection" id="rejection" style="width: 1200px;" placeholder="Reject?">
        <br>
        <br>
        <div class="text-center">
        <button type='submit' class="btn btn-outline-info" style="width: 15%;">Reject</button>
        </div>
    </form>
        <div class="text-center">
    <a href="{% url 'schedule_advisor:approval' student.id %}"><button class="btn btn-outline-info" style="width: 15%;">Approve</button></a>
        </div>
        <br>
        </div>
    <br>
    <br>
          {% for course in student.shopping_cart.all %}
              <div class="col-md-4 col-sm-6 col-lg-3">
                <div class="card">
                    <div class="card-body text-center">
                      <p class="card-title">{{ course.subject }} {{ course.catalog_number}}</p>
                        <p>{{course.descr}}</p>
                        {% for meet in course.meeting.all %}
                            {% if meet.days|default:'' == '-' and meet.st_time|default:'' == ':' and meet.end_time|default:'' == ':' %}
                                <p>No official meeting time.</p>
                            {% else %}
                            <p>{{meet.days}}: {{meet.st_time}}-{{meet.end_time}}</p>
                            {% endif %}
                            {% endfor %}
                        <u><p>{{course.class_nbr}}</p></u>
                        <p>{{course.enrollment}}/{{course.class_capacity}}</p>
                        {% for instructor in course.instructors.all %}
                            <p>{{instructor.name}} - {{instructor.email}}</p>
                        {% endfor %}
                      <hr>
                            <a href="/courses/{{course.id}}"
                        ><input
                        type="submit"
                        value="Learn More"
                        class="btn btn-danger btn-sm"
                        type="button"
                        /></a>
                    </div>
                </div>
                <br><br><br>
              </div>
          {% endfor %}
            </div>
        </div>
{% endblock %}